// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("DestinationIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int>("MLModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("IX_Alerts_DetectedAt");

                    b.HasIndex("MLModelId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_Alerts_Severity");

                    b.HasIndex("SourceIP")
                        .HasDatabaseName("IX_Alerts_SourceIP");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("Backend.Models.BlockedIP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BlockedBy")
                        .HasColumnType("integer");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("BlockedBy");

                    b.HasIndex("IPAddress")
                        .HasDatabaseName("IX_BlockedIPs_IPAddress");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_BlockedIPs_IsActive");

                    b.ToTable("BlockedIPs", (string)null);
                });

            modelBuilder.Entity("Backend.Models.MLModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Accuracy")
                        .HasColumnType("real");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("F1Score")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelFilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float>("Precision")
                        .HasColumnType("real");

                    b.Property<float>("Recall")
                        .HasColumnType("real");

                    b.Property<int>("TotalAnomaliesDetected")
                        .HasColumnType("integer");

                    b.Property<string>("TrainingDataset")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_MLModels_IsActive");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("IX_MLModels_Version");

                    b.ToTable("MLModels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accuracy = 0f,
                            Algorithm = "FastTree",
                            F1Score = 0f,
                            IsActive = true,
                            ModelFilePath = "MLModels/model_v1.zip",
                            Notes = "Modèle initial du projet",
                            Precision = 0f,
                            Recall = 0f,
                            TotalAnomaliesDetected = 0,
                            TrainingDataset = "CICIDS2017",
                            TrainingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "v1.0"
                        });
                });

            modelBuilder.Entity("Backend.Models.NetworkTraffic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("ConnectionsPerSecond")
                        .HasColumnType("real");

                    b.Property<string>("DestinationIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("integer");

                    b.Property<float>("PacketSize")
                        .HasColumnType("real");

                    b.Property<int>("PortsContacted")
                        .HasColumnType("integer");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<float>("SessionDuration")
                        .HasColumnType("real");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("SourcePort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("IX_NetworkTraffics_CapturedAt");

                    b.HasIndex("SourceIP")
                        .HasDatabaseName("IX_NetworkTraffics_SourceIP");

                    b.ToTable("NetworkTraffics", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CriticalCount")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LowCount")
                        .HasColumnType("integer");

                    b.Property<int>("MediumCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TopSourceIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("TopThreatType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalAnomalies")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt")
                        .HasDatabaseName("IX_Reports_GeneratedAt");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@detection.com",
                            PasswordHash = "CHANGE_THIS_HASH",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Backend.Models.Alert", b =>
                {
                    b.HasOne("Backend.Models.MLModel", "MLModel")
                        .WithMany("Alerts")
                        .HasForeignKey("MLModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MLModel");
                });

            modelBuilder.Entity("Backend.Models.BlockedIP", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("BlockedIPs")
                        .HasForeignKey("BlockedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.NetworkTraffic", b =>
                {
                    b.HasOne("Backend.Models.Alert", "Alert")
                        .WithMany("NetworkTraffics")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("Backend.Models.Alert", b =>
                {
                    b.Navigation("NetworkTraffics");
                });

            modelBuilder.Entity("Backend.Models.MLModel", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("BlockedIPs");
                });
#pragma warning restore 612, 618
        }
    }
}
